image: docker:latest

services:
  - name: docker:dind
    command: ["--tls=false"]

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:latest
  DOCKER_HOST: tcp://docker:2375
  POSTGRES_DB: test_db
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: secure_password

stages:
  - build
  - test
  - deploy

build_image:
  stage: build
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin "$CI_REGISTRY"
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  artifacts:
    paths:
      - docker-compose.yml

test:
  stage: test
  script:
    - apk add --no-cache postgresql-client
    - docker-compose -f docker-compose.yml up -d db_test
    - |
      echo "Waiting for PostgreSQL to be ready..."
      until pg_isready -h db_test -U runner -d test_db_test; do
        sleep 2
      done
    - docker-compose -f docker-compose.yml run --rm tests pytest /app/tests -v || exit 1

deploy:
  stage: deploy
  only:
    - main
  environment:
    name: production
  script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - docker-compose -f docker-compose.prod.yml up -d