stages:
  - deploy

deploy_to_server:
  stage: deploy
  script:
    - echo "Deploying..."
    - docker-compose down
    - docker-compose up -d --build
  after_script:
    - echo "Cleaning up..."
    - docker system prune -f