stages:
  - build
  - tests
  - deploy

build:
  stage: build
  script:
    - echo "build..."
    - docker-compose build

tests:
  stage: tests
  script:
    - echo "testing..."
    - docker-compose build
    - docker-compose run --rm tests || exit 1

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
    - docker-compose down
    - docker-compose up -d --build
  after_script:
    - echo "Cleaning up..."
#    - docker system prune -f