FROM python:3.12-slim

WORKDIR /app

COPY backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# запуск тестов и корректные логи
CMD ["pytest", "backend/tests", "-v", "--tb=short", "-q"]