services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data.sql

#      - postgres_data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/data.sql
volumes:
  postgres_data:
#  backend:
#    build: ./backend
#    ports:
#      - "5000:5000"
#    depends_on:
#      - db
#    environment:
#      DATABASE_URL: postgresql://postgres:postgres@db:5432/coworking
#      FLASK_ENV: development
#

#
