version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - booking-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - admin_username=${admin_username}
      - admin_password=${admin_password}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/static:/app/static
    networks:
      - booking-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"    # 2. Порт оставляем как есть (3000 для dev-сервера)
    volumes:
      - ./frontend:/app
      - /app/node_modules  # 3. Добавляем том для node_modules
    environment:
      - NODE_ENV=development  # 4. Явно указываем окружение
    depends_on:
      - backend
    networks:
      - booking-network

volumes:
  postgres_data:

networks:
  booking-network:
    driver: bridge
